services:
  localstack:
    image: localstack/localstack:3.3
    deploy:
      replicas: 1
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      DEBUG: 1
      ES_CUSTOM_BACKEND: "http://elasticsearch:9200"
      LS_LOG: "error,warn,warning"
    volumes:
      - localstack_lib:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - minio
    networks:
      default:
        ipv4_address: 192.168.1.150

  elasticsearch:
    image: elasticsearch:7.17.8
    deploy:
      replicas: 1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elastic-localstack
      cluster.name: elastic-localstack
      discovery.type: single-node
      xpack.security.enabled: true
      bootstrap.memory_lock: true
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z-cpuv1
    deploy:
      replicas: 1
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - mdata:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}


networks:
  default:
    name: localstack
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  localstack_lib:
  esdata:
  mdata: